<?php
declare(strict_types=1);

namespace Tests\Validation\Validators;

use Bigcommerce\ORM\Entities\Customer;
use Bigcommerce\ORM\Mapper;
use Bigcommerce\ORM\Validation\Validators\EmailValidator;
use Tests\BaseTestCase;

class EmailValidatorTest extends BaseTestCase
{
    /** @var \Bigcommerce\ORM\Validation\Validators\EmailValidator */
    protected $validator;

    /** @var \Bigcommerce\ORM\Mapper */
    protected $mapper;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mapper = new Mapper();
    }

    /**
     * @covers \Bigcommerce\ORM\Validation\Validators\EmailValidator::__construct
     * @covers \Bigcommerce\ORM\Validation\Validators\EmailValidator::validate
     * @throws \Bigcommerce\ORM\Exceptions\MapperException
     * @throws \Doctrine\Common\Annotations\AnnotationException
     */
    public function testValidate()
    {
        $this->validator = new EmailValidator($this->mapper);

        $entity = new Customer();
        $property = $this->mapper->getProperty($entity, 'email');
        $annotation = new \Bigcommerce\ORM\Annotations\Email([]);

        $entity->setEmail(null);
        $result = $this->validator->validate($entity, $property, $annotation);
        $this->assertEquals(true, $result);

        $entity->setEmail('ken.ngo@bigcommerce.com');
        $result = $this->validator->validate($entity, $property, $annotation);
        $this->assertEquals('ken.ngo@bigcommerce.com', $result);
    }

}