<?php
declare(strict_types=1);

namespace Tests;

use Bigcommerce\ORM\Annotations\Resource;
use Bigcommerce\ORM\Entities\Customer;
use Bigcommerce\ORM\Mapper;

class MapperTest extends BaseTestCase
{
    /** @var \Bigcommerce\ORM\Mapper */
    protected $mapper;

    /** @var \Bigcommerce\ORM\Entities\Customer */
    protected $customer;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->mapper = new Mapper();
        $this->customer = new Customer();
    }

    /**
     * @covers \Bigcommerce\ORM\Mapper::getObjectType
     * @throws \Bigcommerce\ORM\Exceptions\MapperException
     */
    public function testGetObjectType(){
        $objectType = $this->mapper->getObjectType($this->customer);
        $this->assertEquals('Customer', $objectType);
    }

    /**
     * @covers \Bigcommerce\ORM\Mapper::getClassAnnotation
     * @throws \Bigcommerce\ORM\Exceptions\MapperException
     */
    public function testGetClassAnnotation(){
        $classAnnotation = $this->mapper->getClassAnnotation($this->customer);
        $this->assertInstanceOf(Resource::class, $classAnnotation);
        $this->assertEquals('Customer', $classAnnotation->name);
        $this->assertEquals('/customers', $classAnnotation->path);
        $this->assertNull($classAnnotation->parentField);
    }
}