<?php
declare(strict_types=1);

namespace Tests;

use Bigcommerce\ORM\QueryBuilder;

class QueryBuilderTest extends BaseTestCase
{
    /** @var \Bigcommerce\ORM\QueryBuilder */
    protected $queryBuilder;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->queryBuilder = new QueryBuilder();
    }

    /**
     * @covers \Bigcommerce\ORM\QueryBuilder::select
     */
    public function testSelect()
    {
        $this->queryBuilder->select('id');
        $query = $this->queryBuilder->getQueryString();
        $this->assertEquals('include_fields=id', $query);

        $this->queryBuilder->select(['company', 'name']);
        $query = $this->queryBuilder->getQueryString();
        $this->assertEquals('include_fields=id,company,name', $query);
    }

}